export const PRODUCTS_LIST_SUCCESS = "PRODUCTS_LIST_SUCCESS";
export const PRODUCTS_LIST_LOADING = "PRODUCTS_LIST_LOADING";
export const PRODUCTS_LIST_ERROR = "PRODUCTS_LIST_ERROR";
export const INSERT_PRODUCT_SUCCESS = "INSERT_PRODUCT_SUCCESS";
export const UPDATE_PRODUCT_SUCCESS = "UPDATE_PRODUCT_SUCCESS";
export const UPDATE_PRODUCT_LOADING = "UPDATE_PRODUCT_LOADING";
export const UPDATE_PRODUCT_ERROR = "UPDATE_PRODUCT_ERROR";

export const SET_PRODUCT_EDIT = "SET_PRODUCT_EDIT";
