export const GET_PRODUCTS_SUCCESS = "GET_PRODUCTS_SUCCESS";
export const PUBLISH_PRODUCT = "PUBLISH_PRODUCT";
export const UPDATE_PRODUCT = "UPDATE_PRODUCT";
export const SET_PRODUCT_EDIT_MODE = "SET_PRODUCT_EDIT_MODE";
export const UPDATE_TOTAL_ITEMS = "UPDATE_TOTAL_ITEMS";
