export const GET_PRODUCTS_LIST_SUCCESS = "GET_PRODUCTS_LIST_SUCCESS";
export const GET_PRODUCTS_LIST_LOADING = "GET_PRODUCTS_LIST_LOADING";
export const GET_PRODUCTS_LIST_ERROR = "GET_PRODUCTS_LIST_ERROR";
export const PUBLISH_PRODUCT = "PUBLISH_PRODUCT";
export const UPDATE_PRODUCT = "UPDATE_PRODUCT";
export const SET_PRODUCT_EDIT_MODE = "SET_PRODUCT_EDIT_MODE";
export const UPDATE_TOTAL_ITEMS = "UPDATE_TOTAL_ITEMS";
